In [12]:
import numpy as np
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [13]:
print(type(x))
print(x.shape)
print(x.size)   #toplam veri sayısı
print(x.ndim)  #boyut
print(x.nbytes ) #depolanan veri bytı 
print(x.dtype)   #veri tipi

<class 'numpy.ndarray'>
(4,)
4
1
16
int32


In [16]:
y = np.array([[1,2,3],[4,5,6]])

print(y)
print(type(y))
print(y.shape)  #2 satır 3 sütun
print(y.size)   #toplam veri sayısı
print(y.ndim)  #boyut
print(y.nbytes)  #depolanan veri byte
print(y.dtype)  

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6
2
24
int32


In [17]:
z=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

print(z)
print(type(z))
print(z.shape)  #2 satır 3 sütun
print(z.size)   #toplam veri sayısı
print(z.ndim)  #boyut
print(z.nbytes)  #depolanan veri byte
print(z.dtype)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
<class 'numpy.ndarray'>
(2, 2, 2)
8
3
32
int32


In [18]:
x=np.array([1,2,3,4])
print(x.dtype)  #ndarraylar hepsi aynı veri tipidir

x=np.array([1,'2',3])
print(x.dtype)  #unicode, karışık veri_tipi yani   YANİ BÜTÜN HER ŞEYİ STRİNGE ÇEVİRDİ NUMPY

z=np.array([1,2.0,3])
print(z.dtype)  # NUMPY HEPSİNİ FLOATA ÇEVİRDİ   #BU DURUMA UPCASTİNG DENİLİYOR

f=np.array([1,0.1,"n"])
print(f.dtype)

int32
<U11
float64
<U32


In [19]:
a= np.array([1,2,3])
a=np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
a=np.zeros((3,2)) ## full 0
a=np.ones((4,3))  ## full 1
a=np.arange(0,10,2) # ne anlama geldiğini anlarsın zaten
a=np.linspace(1,10,5)  # 1 ile 10 arasında 5 tane sayı üretiyor 1 ve 10 en başta ve sonra aralarındaki sayılarda eşit uzaklıkta olacak şekilde
a=np.full((2,2),7) ## (2,2) lik bir array oluştur ve 7 ile doldur
print(a.shape) 
print(a)

(4, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
a=np.array([1,2,3])
z=a.view()
f = a.copy()  # copy olarak alırsan copy'i değiştirsen copy değişir, ama view'den bir şey değiştirirsen bütün array değişir
z[0] = 13
a[2] = 14
f[1] = 7
print(a)
print(z)
print(f)

[13  2 14]
[13  2 14]
[1 7 3]


In [25]:
f=np.array([1.2,3.4,5.6],dtype=np.int32)
print(f)
print(f.dtype)

z=np.array([3,4,5],dtype=np.float64)  #bu işlemlere downcast deniliyor.
print(z)
print(z.dtype)

[1 3 5]
int32
[3. 4. 5.]
float64


In [29]:
x= np.array([1,2,3,4],dtype=np.float64)

x=x.astype(np.complex64)  #karmaşık sayılara çeviriyor. complex64 bir veri tipi
print(x)
# x = x.astype(float)
# print(x)
print(x.dtype)

[1. 2. 3. 4.]
float64


In [30]:
x1=np.array([1,2,3],dtype=np.int32)
x2=np.array([5.2,2.8,4.8],dtype=np.float64)

print(x1+x2)
print((x1+x2).dtype)

[6.2 4.8 7.8]
float64


In [33]:
y = np.array([4,9,16,25])
x = np.sqrt(y)
print(x)
print(x.dtype)

[2. 3. 4. 5.]
float64


In [34]:
x1=np.zeros(4)  #x1=np.zeros(4,dtype="int32") BÖYLE YAPARSAK İNT OLARAK VERİLERİ ALIRIZ.
print(x1)
print(x1.dtype)

[0. 0. 0. 0.]
float64


In [35]:
y1=np.ones(4)
print(y1)
print(y1.dtype)

[1. 1. 1. 1.]
float64


In [38]:
x2=np.zeros((2,3,4),dtype=np.int32)  #3 BOYUTLU ARRAY 
print(x2)
print()
y2=np.ones((3,2))
print(y2)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
x=np.full((2,3),10) #10 SAYISI SABİT SAYIDIR BİZ HANGİ SAYIYI YAZMAK İSTİYORSAK ONU YAZARIZ ORAYA
x

array([[10, 10, 10],
       [10, 10, 10]])

In [41]:
y=10.0*np.ones((2,3))

z=10.0+np.zeros((2,3))
print(y)
print()
print(z)

[[10. 10. 10.]
 [10. 10. 10.]]

[[10. 10. 10.]
 [10. 10. 10.]]


In [58]:
x=np.eye(4)
print(x)
print()
y=np.eye(5,4) #eye fonk tuple şeklinde yazmana gerek yok
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [59]:
x=np.eye(6)
print(x)
print()
y=np.eye(6,k=1)
print(y)
print()
z=np.eye(6,k=-2)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [61]:
x=np.identity(5)
print(x)#EYE FONKSİYONUYLA AYNI İŞLEVDE
print()

x=np.diag([4,7,11,3])  ## diagonellerde bu sayılar olacak şekilde bir kare matrix oluştur diyoruz.
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[ 4  0  0  0]
 [ 0  7  0  0]
 [ 0  0 11  0]
 [ 0  0  0  3]]


In [66]:
x=np.arange(7)  
print(x)#MANTIĞINI ANLARSIN KOLAY
y=np.arange(4,19,2)#START, STOP,STEP   ### ve tek boyutlu bir array veriyor
print(y)
print()
x=np.linspace(0,15,10) #10 TANE RAKAM DÖNÜYOR 0 VE 15 DAHİL, bu da tek boyutlu
print(x)

[0 1 2 3 4 5 6]
[ 4  6  8 10 12 14 16 18]

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [67]:
x=np.arange(20)
print(x)
print()
y=np.reshape(x,(4,5))
print(y)
print()
z=np.reshape(x,(2,2,5))
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [69]:
x=np.linspace(0,19,20)
print(x)
print()
y=np.reshape(x,(2,10))
print(y)
print()
z=np.linspace(0,19,20).reshape(2,10) #TEK SATIRDA DA YAZABİLİRİZ KODU
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [70]:
x=np.random.random((2,3)) #MATRİSİN ELEMANLARI 0,1 ARASINDA OLUR AMA 1 DAHİL DEĞİLDİR
print(x)
print()
x=np.random.randint(3,12,size=(3,2))#BAŞLANGIÇ NOKTASINI VE BİTİŞ NOKTASINI ALIYORSUN VE MATRİSİ VERİYORSUN İNT OLARAK ÇIKTI ALIYORSUN 
print(x)

[[0.85833415 0.93846601 0.919527  ]
 [0.99841763 0.84015151 0.51509952]]

[[ 9  6]
 [ 4  6]
 [ 9 11]]


In [71]:
x=np.arange(5)
print(x)
print(x[0])
print(x[2])
print(x[-5])
print(x[-1])

x[2]=200
print(x)

[0 1 2 3 4]
0
2
0
4
[  0   1 200   3   4]


In [ ]:
x=np.arange(12).reshape(3,4)
print(x)
print()
print(x[0,0])
print(x[1,3])

x[0,0]=100
print(x[0,0])

In [ ]:
x=np.array((4,6,0,2,7))
print(x)
y=np.delete(x,[0,2])#BURADA İNDEX VERİYORUZ np.arange() yapsakta aynı olur , 0. indexi ve 2. indexi sildik
print(y)
print(x)


In [ ]:

#AXİS=0 ROW ,AXİS=1 COLUMN

x = np.arange(16).reshape(4,4)
print(x)
x = np.delete(x,1,axis=0)
print()
print(x)

x=np.delete(x,[0,2],axis=1)
print()
print(x)

In [ ]:
x=np.arange(5)
print(x)
x=np.append(x,100)
print(x)
x=np.append(x,[200,300])
print(x)

In [74]:
x=np.arange(9).reshape(3,3)
print(x)
x=np.append(x,[[100,200,300]],axis=0)  # Burada 2 tane parantez ile veriyi göndermen gerekiyor.Bir dataframe olarak gönderiyoruz öyle düşün
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]


In [76]:
x=np.arange(9).reshape(3,3)
x=np.append(x,[[10],[20],[30]],axis=1) 
print(x)

[[ 0  1  2 10]
 [ 3  4  5 20]
 [ 6  7  8 30]]


In [ ]:
x=np.arange(5)
print(x)
x=np.insert(x,1,10)#ilk kısım array ikincisi index üçüncü yerleştirmek istediğimiz element son kısım axis
print(x)
x=np.insert(x,1,[10,20]) 
print(x)

In [79]:
x=np.arange(9).reshape(3,3)
print(x)
x=np.insert(x,1,[100,200,300],axis=0)
print(x)
print()
##x=np.insert(x,0,[[10,20,30]],axis=1) #APPEND EDERKEN AYRI AYRI LİSTE HALİNE ALIYORUZ 
##print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [100 200 300]
 [  3   4   5]
 [  6   7   8]]



In [83]:
x=np.arange(3)
y=np.arange(9).reshape(3,3)

z=np.vstack((x,y))#X İ Y NİN TEPESİNE KOY DEMEK VERTİCAL STACK
print(z)
print()
t=np.hstack((x,y.reshape(9,)))#HORİZOTAL STACK   #FARKETTİYSEN ÖNCE Y NİN MATRİSİNİ DEĞİŞTİRİYRUZ SONRA BİRLEŞTİRİYORUZ.
print(t)


[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2 0 1 2 3 4 5 6 7 8]


In [ ]:
#SLİCİNG AND COPY

x=np.arange(10)
print(x)
print()
print(x[2:6])#2.indexten 6.indexe doğru ama 6 alınmıyor tabi
print(x[4:])
print(x[:7])
print(x[:-1])
print(x[-4:-2])

In [ ]:
x=np.arange(25).reshape(5,5)
print(x)
print()
y=x[0:3,1:4]
print(y)
print()
z=x[2:]
print(z)
print()
t=x[::]
print(t)
print()
v=x[:,3:]
print(v)

In [84]:
x=np.arange(9)
y=x.reshape(3,3)

z=y[1:2,0:2]
print(z)

y[0,0]=100
print(y)
print()
print(x)#X TE DEĞİŞİKLİĞE UĞRADI FARK ET

print(np.shares_memory(x,y))#YANİ X İLE Y DEKİ DEĞİŞİKLİKLER BİRBİRİNİ ETKİLER ,HAFIZADAKİ YERLER AYNI YERDE TUTULUR.

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4]]
[[100   1   2]
 [  3   4   5]
 [  6   7   8]]

[100   1   2   3   4   5   6   7   8]
True


In [86]:
x=np.arange(16).reshape(4,4)
y=np.copy(x[0:3,1:3])

print(np.shares_memory(x,y))#COPY

y[0,0]=100

print(y)
print(x)
print()
z=x[1:2,1:2].copy()
print(z)

print(np.shares_memory(x,z))


False
[[100   2]
 [  5   6]
 [  9  10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[5]]
False


In [ ]:
#FANCY İNDEXİNG AND BOOLEAN İNDEXİNG

x=np.linspace(1,21,11)
print(x)

y=np.array((2,4,7))
print(y)
print()
print(x[y]) #önce 2.indexteki elemanı gösterdi sonra 4 indexteki en sonda 7 indexteki


In [89]:
x=np.arange(25).reshape(5,5)
y=np.array((1,2))

print(x[y,:]) #index 1 ve 2 yi alıyor.
print()
print(x[:,y])
print()

z=x[y,:]
print(z)
z[0,0]=100
print()
print(z)
print()
print(x)# ORJİNAL NDARRAY DEĞİŞMEDİ BUNA FANCY ANDARRAY DENİLİYOR. X BİZİM ORJİNAL NDARRAYİMİZDİ SONRA Y Yİ OLUŞTURDUK SONRA Z Yİ OLUŞTURDUK VE Z Yİ DEĞİŞTİRDİK PRİNT YAPTIĞIMIZDA DA X DEĞİŞMEDİĞİNİ GÖRDÜK
print(np.shares_memory(x,y))#fancy indexing

[[ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]

[[ 5  6  7  8  9]
 [10 11 12 13 14]]

[[100   6   7   8   9]
 [ 10  11  12  13  14]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
False


In [91]:
x=np.arange(10)

print(x[x%2==0])#x in elemanları iki ile bölünenleri 0 olanları bana yaz
z=x[x%2==0]
print(z)
print()
print(x) #FANCY VE BOOLİNG İNDEXTE YAPILAN DEĞİŞİKLER ANA İNDEXİ ETKİLEMİYOR 

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]

[0 1 2 3 4 5 6 7 8 9]


In [92]:
x=np.random.randint(10,size=10) #Rastgele 10 tane sayı üretiliyor.
y=np.random.randint(10,size=10)

print(x>y)
print(type(x>y)) 
print((x>y).dtype)

print()
print(np.all(x>y)) #HEPSİ BÜYÜK MÜ DİYOR
print(np.any(x>y)) #SADECE BİRİ BİLE OLSA BÜYÜK MÜ DİYOR

[False False  True False  True False  True False  True  True]
<class 'numpy.ndarray'>
bool

False
True


In [95]:
x=np.linspace(1,21,11)

mask=(x%3==0)

print(x[mask])#diyoruz ki bize bu mask değerinden true olanları (elemanları) göster

x[mask]=-1
print(x)

[ 3.  9. 15. 21.]
[ 1. -1.  5.  7. -1. 11. 13. -1. 17. 19. -1.]


In [96]:
x=np.array([2,5,3,6,9])
y=np.array([6,1,8,7,3])

print(np.intersect1d(x,y)) #ORTAK ELEMANLARI ALIYOR VE PRİNTLİYOR
print(type(np.intersect1d(x,y))) 


print(np.setdiff1d(x,y)) #X TE OLUP Y DE OLMAYAN ELEMANLARI GÖSTERECEK
print(np.setdiff1d(y,x))#Y DE OLUP X TE OLMAYANLAR


print(np.union1d(x,y)) 
print(np.in1d(x,y))

[3 6]
<class 'numpy.ndarray'>
[2 5 9]
[1 7 8]
[1 2 3 5 6 7 8 9]


In [97]:
z=np.array([2,5,3,6,9,1,0,5,2,3,3])

print(np.unique(z)) #bir matrste birden fazla olan elemanları tek bir defa alıp printliyor aslında set() fonksiyonuna benzer.

z=np.random.randint(1,10,size=(10,))
print(z)
print(np.sort(z))
print(z)#ORJİNAL ARRAYDE DEĞİŞİKLİK YOK


[0 1 2 3 5 6 9]
[6 7 2 3 5 3 7 4 6 7]
[2 3 3 4 5 6 6 7 7 7]
[6 7 2 3 5 3 7 4 6 7]


In [98]:
y=np.random.randint(1,10,size=(10,))
y.sort()
print(y)

[6 9 3 3 9 5 3 1 4 1]
[1 1 3 3 3 4 5 6 9 9]


In [99]:
x=np.random.randint(1,10,size=(5,5))
print(x)
print()
print(np.sort(x,axis=0))
print()
print(np.sort(x,axis=1))
print()
print(np.sort(x))  # BU HEM COLUMN İÇİN HEM ROW İÇİN SIRALIYOR.

[[9 5 4 4 6]
 [9 2 6 2 7]
 [7 7 8 1 6]
 [3 8 7 9 9]
 [4 7 3 9 5]]

[[3 2 3 1 5]
 [4 5 4 2 6]
 [7 7 6 4 6]
 [9 7 7 9 7]
 [9 8 8 9 9]]

[[4 4 5 6 9]
 [2 2 6 7 9]
 [1 6 7 7 8]
 [3 7 8 9 9]
 [3 4 5 7 9]]

[[4 4 5 6 9]
 [2 2 6 7 9]
 [1 6 7 7 8]
 [3 7 8 9 9]
 [3 4 5 7 9]]


In [102]:
x=np.random.randint(1,10,size=5)
print(x)
y=np.random.randint(1,10,size=5)
print(y)
print(np.sum(x)) # X İN TOPLAMINI VERİYOR
print(x==y)
# 4 İŞLEM YAPARKEN DİKKAT EDİLMESİ GEREKEN EN ÖNEMLİ ŞEY BOYUTLARI VE ELEMAN SAYILARI EŞİT OLMASI LAZIM EĞER EŞİT DEĞİLLERSE KOD HATA VERİR.
print(np.array_equal(x,y))#BURADA HER ELEMAN AYNI MI DİYE SORUYORUZ
print(x+y)#indexlere göre toplama yapıyor
print(np.add(x,y))#print(x+y)'nin farklı bir yazılışı
print(type(x+y))

print()
print(x-y)
print(np.subtract(x,y))
print()

print(x*y)
print(np.multiply(x,y))
print()

print(x/y)
print(np.divide(x,y))

[4 5 4 8 6]
[3 9 8 6 7]
27
[False False False False False]
False
[ 7 14 12 14 13]
[ 7 14 12 14 13]
<class 'numpy.ndarray'>

[ 1 -4 -4  2 -1]
[ 1 -4 -4  2 -1]

[12 45 32 48 42]
[12 45 32 48 42]

[1.33333333 0.55555556 0.5        1.33333333 0.85714286]
[1.33333333 0.55555556 0.5        1.33333333 0.85714286]


In [101]:
print(x+3)
print(x-3)
print(x*3)
print(x/3)

print(np.sqrt(x))#KAREKÖKLERİNİ ALIYOR
print(np.power(x,3))#X İN KÜPÜNÜ ALIYORUZ
print(np.exp(x))

[12  4 10 10  7]
[ 6 -2  4  4  1]
[27  3 21 21 12]
[3.         0.33333333 2.33333333 2.33333333 1.33333333]
[3.         1.         2.64575131 2.64575131 2.        ]
[729   1 343 343  64]
[8.10308393e+03 2.71828183e+00 1.09663316e+03 1.09663316e+03
 5.45981500e+01]


In [ ]:
x=np.random.randint(1,10,size=9).reshape(3,3)
print(x)
print(x.sum(axis=0))#sütun toplamı
print(x.sum(axis=1))#satır toplamı
print(x.min())
print(x.max())
print(np.sum(x,axis=0)) #BÖYLE DE YAPABİLİRSİN. SANA KALMIŞ FIRAT
print(x.argmin())# EN KÜÇÜK ELEMANIN İNDEX SIRASI
print(x.argmax())#EN BÜYÜK ELEMANIN İNDEX SIRASI 

In [103]:
x=np.random.randint(1,10,size=8)
print(x)
print()

print(x.mean())#ARİTMATİK ORTALAMA
print(np.median(x))#medyan
print(x.std())#standart sapma

[3 4 6 3 9 5 6 7]

5.375
5.5
1.9324531042175384


In [105]:
x=np.random.randint(1,10,size=(2))#ŞEKLİN GERİ KALANINI DOLDURUYORUZ+
print(x)
print()
y=np.random.randint(1,10,size=(3,2))
print(y)
print()

###BROADCASTİNG(AYNI SHAPE SAHİP OLMAYANLAR İÇİN)

print(x+y)

[2 9]

[[9 7]
 [1 6]
 [6 8]]

[[11 16]
 [ 3 15]
 [ 8 17]]
